cask_args appdir: '/Applications'

cask 'font-jetbrains-mono-nerd-font'
cask 'nikitabobko/tap/aerospace'

tap 'FelixKratz/formulae'
brew 'borders'

tap 'cormacrelf/tap'
brew 'dark-notify'

brew 'zinit'
brew 'starship'
brew 'mise'
brew 'eza'
brew 'zoxide'
brew 'delta'
brew 'lazygit'
brew 'bat'
brew 'docker'
brew 'fd'
brew 'fzf'
brew 'glow'
brew 'gpg2'
brew 'grc'
brew 'htop'
brew 'imagemagick'
brew 'iproute2mac'
brew 'lnav'
brew 'maven'
brew 'pinentry-mac'
brew 'prettyping'
brew 'tldr'
brew 'tree'
brew 'tmux'
